' =======================================
' Iniciar.vbs – lanzador principal portable (FIX FINAL)
' =======================================
Option Explicit

Dim shell, fso, basePath
Set shell = CreateObject("WScript.Shell")
Set fso   = CreateObject("Scripting.FileSystemObject")

basePath = fso.GetParentFolderName(WScript.ScriptFullName)

If Not fso.FolderExists(basePath & "\venv") Then
    MsgBox "No se encontró la carpeta venv.", 16, "Error"
    WScript.Quit
End If

If Not fso.FileExists(basePath & "\ui_main.py") Then
    MsgBox "No se encontró ui_main.py.", 16, "Error"
    WScript.Quit
End If

' ================= INSTALAR ACCESO DIRECTO (FORMA SEGURA) =================
If fso.FileExists(basePath & "\Instalar_acceso_directo.ps1") Then
    Dim psCmd
    psCmd = "powershell.exe -NoProfile -ExecutionPolicy Bypass -Command " & _
            """& '" & basePath & "\Instalar_acceso_directo.ps1'"""
    shell.Run psCmd, 0, True
End If

' ================= EJECUTAR LA APLICACIÓN =================
Dim pythonExe, pythonArgs
pythonExe  = basePath & "\venv\Scripts\pythonw.exe"
pythonArgs = """" & basePath & "\ui_main.py"""

If fso.FileExists(pythonExe) Then
    shell.Run """" & pythonExe & """ " & pythonArgs, 0, False
Else
    MsgBox "No se encontró pythonw.exe.", 16, "Error"
End If

'' SIG '' Begin signature block
'' SIG '' MIIcswYJKoZIhvcNAQcCoIIcpDCCHKACAQExCzAJBgUr
'' SIG '' DgMCGgUAMGcGCisGAQQBgjcCAQSgWTBXMDIGCisGAQQB
'' SIG '' gjcCAR4wJAIBAQQQTvApFpkntU2P5azhDxfrqwIBAAIB
'' SIG '' AAIBAAIBAAIBADAhMAkGBSsOAwIaBQAEFNtZ7zK9q5+r
'' SIG '' CZ+ixbEH3b5NhxwNoIIW2jCCA5wwggKEoAMCAQICEBta
'' SIG '' GkbAXEq3T+Yw1HG/oQswDQYJKoZIhvcNAQELBQAwZjEb
'' SIG '' MBkGA1UECgwSVHJhbnNjcmliZSBQcm9qZWN0MSIwIAYJ
'' SIG '' KoZIhvcNAQkBFhNwaGFybWFrb3pAZ21haWwuY29tMSMw
'' SIG '' IQYDVQQDDBpXYWx0ZXIgUGFibG8gVMOpbGxleiBBeWFs
'' SIG '' YTAeFw0yNjAyMDMwMDAzMjJaFw0yNzAyMDMwMDIzMjJa
'' SIG '' MGYxGzAZBgNVBAoMElRyYW5zY3JpYmUgUHJvamVjdDEi
'' SIG '' MCAGCSqGSIb3DQEJARYTcGhhcm1ha296QGdtYWlsLmNv
'' SIG '' bTEjMCEGA1UEAwwaV2FsdGVyIFBhYmxvIFTDqWxsZXog
'' SIG '' QXlhbGEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
'' SIG '' AoIBAQDHCOMmvceuWvj3g8oS9WJxitVV57d7gP41njUw
'' SIG '' tPaCOZQ3MN7WhPGRgXuRbpXcPTEe4+XvVC8qOdKirjsM
'' SIG '' AvJCYKIqV3OEgflmBEs5oZelRlLd3gH2SgxjS1hqQMz8
'' SIG '' sZLSaM1n9k2dDph1CNroRdWNZA+oH3FjyGigiHHgevOQ
'' SIG '' 7iNZrutBessexKGyL2NNUa3c18mz13hJY0jKFzwNI0zu
'' SIG '' urC/yiud3rMkTNkSW8uUm2OLAbotgJwLBurK7O/8eBGq
'' SIG '' +sdfCzSYL3yzqN+apcsVhhzWrjVk2wFm6Tv8JCsR/Q4A
'' SIG '' f1JCFJa1pYWd2QmBIyy+P1Ig0zvb2prQMBFJFbERAgMB
'' SIG '' AAGjRjBEMA4GA1UdDwEB/wQEAwIHgDATBgNVHSUEDDAK
'' SIG '' BggrBgEFBQcDAzAdBgNVHQ4EFgQUO4Ku7LtNVxMWeieG
'' SIG '' VTfEN1pz4WEwDQYJKoZIhvcNAQELBQADggEBAFGDr/Ur
'' SIG '' Hnxe3wMwfQvme9gv6vNFkOI/7lfDX6SQOhIZQ1dXTtsb
'' SIG '' /79fZo2ARaV/b2JUVGZaW8N2+sFeMgtjuiQVX/PXB7tL
'' SIG '' dx54f4z7dauBktUm11Db/XkaCsY3ZoB1hxMlnWexqZqr
'' SIG '' 7c88rYH5wN6zSzNX7fHUcimEer5l83RJPo4O+3DsvTru
'' SIG '' PGdb8bfRZUYdi0dmu2Sf4ebvZkSZGV1wtEoxJp2Crjtj
'' SIG '' mKJfRBWjRLqHSdPkfylT0Ku6Agz4HSXxLZC0aylcrdEf
'' SIG '' xNvwwrT4U2gGREF7kAuRjWxa+/us0qMBfW/3OPNUPh+n
'' SIG '' jspGHViHaOnyDW73NXNdeD0xS9EwggWNMIIEdaADAgEC
'' SIG '' AhAOmxiO+dAt5+/bUOIIQBhaMA0GCSqGSIb3DQEBDAUA
'' SIG '' MGUxCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2Vy
'' SIG '' dCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20x
'' SIG '' JDAiBgNVBAMTG0RpZ2lDZXJ0IEFzc3VyZWQgSUQgUm9v
'' SIG '' dCBDQTAeFw0yMjA4MDEwMDAwMDBaFw0zMTExMDkyMzU5
'' SIG '' NTlaMGIxCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdp
'' SIG '' Q2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j
'' SIG '' b20xITAfBgNVBAMTGERpZ2lDZXJ0IFRydXN0ZWQgUm9v
'' SIG '' dCBHNDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
'' SIG '' ggIBAL/mkHNo3rvkXUo8MCIwaTPswqclLskhPfKK2FnC
'' SIG '' 4SmnPVirdprNrnsbhA3EMB/zG6Q4FutWxpdtHauyefLK
'' SIG '' EdLkX9YFPFIPUh/GnhWlfr6fqVcWWVVyr2iTcMKyunWZ
'' SIG '' anMylNEQRBAu34LzB4TmdDttceItDBvuINXJIB1jKS3O
'' SIG '' 7F5OyJP4IWGbNOsFxl7sWxq868nPzaw0QF+xembud8hI
'' SIG '' qGZXV59UWI4MK7dPpzDZVu7Ke13jrclPXuU15zHL2pNe
'' SIG '' 3I6PgNq2kZhAkHnDeMe2scS1ahg4AxCN2NQ3pC4FfYj1
'' SIG '' gj4QkXCrVYJBMtfbBHMqbpEBfCFM1LyuGwN1XXhm2Tox
'' SIG '' RJozQL8I11pJpMLmqaBn3aQnvKFPObURWBf3JFxGj2T3
'' SIG '' wWmIdph2PVldQnaHiZdpekjw4KISG2aadMreSx7nDmOu
'' SIG '' 5tTvkpI6nj3cAORFJYm2mkQZK37AlLTSYW3rM9nF30sE
'' SIG '' AMx9HJXDj/chsrIRt7t/8tWMcCxBYKqxYxhElRp2Yn72
'' SIG '' gLD76GSmM9GJB+G9t+ZDpBi4pncB4Q+UDCEdslQpJYls
'' SIG '' 5Q5SUUd0viastkF13nqsX40/ybzTQRESW+UQUOsxxcpy
'' SIG '' FiIJ33xMdT9j7CFfxCBRa2+xq4aLT8LWRV+dIPyhHsXA
'' SIG '' j6KxfgommfXkaS+YHS312amyHeUbAgMBAAGjggE6MIIB
'' SIG '' NjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTs1+OC
'' SIG '' 0nFdZEzfLmc/57qYrhwPTzAfBgNVHSMEGDAWgBRF66Kv
'' SIG '' 9JLLgjEtUYunpyGd823IDzAOBgNVHQ8BAf8EBAMCAYYw
'' SIG '' eQYIKwYBBQUHAQEEbTBrMCQGCCsGAQUFBzABhhhodHRw
'' SIG '' Oi8vb2NzcC5kaWdpY2VydC5jb20wQwYIKwYBBQUHMAKG
'' SIG '' N2h0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdp
'' SIG '' Q2VydEFzc3VyZWRJRFJvb3RDQS5jcnQwRQYDVR0fBD4w
'' SIG '' PDA6oDigNoY0aHR0cDovL2NybDMuZGlnaWNlcnQuY29t
'' SIG '' L0RpZ2lDZXJ0QXNzdXJlZElEUm9vdENBLmNybDARBgNV
'' SIG '' HSAECjAIMAYGBFUdIAAwDQYJKoZIhvcNAQEMBQADggEB
'' SIG '' AHCgv0NcVec4X6CjdBs9thbX979XB72arKGHLOyFXqka
'' SIG '' uyL4hxppVCLtpIh3bb0aFPQTSnovLbc47/T/gLn4offy
'' SIG '' ct4kvFIDyE7QKt76LVbP+fT3rDB6mouyXtTP0UNEm0Mh
'' SIG '' 65ZyoUi0mcudT6cGAxN3J0TU53/oWajwvy8LpunyNDzs
'' SIG '' 9wPHh6jSTEAZNUZqaVSwuKFWjuyk1T3osdz9HNj0d1pc
'' SIG '' VIxv76FQPfx2CWiEn2/K2yCNNWAcAgPLILCsWKAOQGPF
'' SIG '' mCLBsln1VWvPJ6tsds5vIy30fnFqI2si/xK4VC0nftg6
'' SIG '' 2fC2h5b9W9FcrBjDTZ9ztwGpn1eqXijiuZQwgga0MIIE
'' SIG '' nKADAgECAhANx6xXBf8hmS5AQyIMOkmGMA0GCSqGSIb3
'' SIG '' DQEBCwUAMGIxCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxE
'' SIG '' aWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2Vy
'' SIG '' dC5jb20xITAfBgNVBAMTGERpZ2lDZXJ0IFRydXN0ZWQg
'' SIG '' Um9vdCBHNDAeFw0yNTA1MDcwMDAwMDBaFw0zODAxMTQy
'' SIG '' MzU5NTlaMGkxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5E
'' SIG '' aWdpQ2VydCwgSW5jLjFBMD8GA1UEAxM4RGlnaUNlcnQg
'' SIG '' VHJ1c3RlZCBHNCBUaW1lU3RhbXBpbmcgUlNBNDA5NiBT
'' SIG '' SEEyNTYgMjAyNSBDQTEwggIiMA0GCSqGSIb3DQEBAQUA
'' SIG '' A4ICDwAwggIKAoICAQC0eDHTCphBcr48RsAcrHXbo0Zo
'' SIG '' dLRRF51NrY0NlLWZloMsVO1DahGPNRcybEKq+RuwOnPh
'' SIG '' of6pvF4uGjwjqNjfEvUi6wuim5bap+0lgloM2zX4kftn
'' SIG '' 5B1IpYzTqpyFQ/4Bt0mAxAHeHYNnQxqXmRinvuNgxVBd
'' SIG '' Jkf77S2uPoCj7GH8BLuxBG5AvftBdsOECS1UkxBvMgEd
'' SIG '' gkFiDNYiOTx4OtiFcMSkqTtF2hfQz3zQSku2Ws3IfDRe
'' SIG '' b6e3mmdglTcaarps0wjUjsZvkgFkriK9tUKJm/s80Fio
'' SIG '' cSk1VYLZlDwFt+cVFBURJg6zMUjZa/zbCclF83bRVFLe
'' SIG '' GkuAhHiGPMvSGmhgaTzVyhYn4p0+8y9oHRaQT/aofEnS
'' SIG '' 5xLrfxnGpTXiUOeSLsJygoLPp66bkDX1ZlAeSpQl92QO
'' SIG '' MeRxykvq6gbylsXQskBBBnGy3tW/AMOMCZIVNSaz7BX8
'' SIG '' VtYGqLt9MmeOreGPRdtBx3yGOP+rx3rKWDEJlIqLXvJW
'' SIG '' nY0v5ydPpOjL6s36czwzsucuoKs7Yk/ehb//Wx+5kMqI
'' SIG '' MRvUBDx6z1ev+7psNOdgJMoiwOrUG2ZdSoQbU2rMkpLi
'' SIG '' Q6bGRinZbI4OLu9BMIFm1UUl9VnePs6BaaeEWvjJSjNm
'' SIG '' 2qA+sdFUeEY0qVjPKOWug/G6X5uAiynM7Bu2ayBjUwID
'' SIG '' AQABo4IBXTCCAVkwEgYDVR0TAQH/BAgwBgEB/wIBADAd
'' SIG '' BgNVHQ4EFgQU729TSunkBnx6yuKQVvYv1Ensy04wHwYD
'' SIG '' VR0jBBgwFoAU7NfjgtJxXWRM3y5nP+e6mK4cD08wDgYD
'' SIG '' VR0PAQH/BAQDAgGGMBMGA1UdJQQMMAoGCCsGAQUFBwMI
'' SIG '' MHcGCCsGAQUFBwEBBGswaTAkBggrBgEFBQcwAYYYaHR0
'' SIG '' cDovL29jc3AuZGlnaWNlcnQuY29tMEEGCCsGAQUFBzAC
'' SIG '' hjVodHRwOi8vY2FjZXJ0cy5kaWdpY2VydC5jb20vRGln
'' SIG '' aUNlcnRUcnVzdGVkUm9vdEc0LmNydDBDBgNVHR8EPDA6
'' SIG '' MDigNqA0hjJodHRwOi8vY3JsMy5kaWdpY2VydC5jb20v
'' SIG '' RGlnaUNlcnRUcnVzdGVkUm9vdEc0LmNybDAgBgNVHSAE
'' SIG '' GTAXMAgGBmeBDAEEAjALBglghkgBhv1sBwEwDQYJKoZI
'' SIG '' hvcNAQELBQADggIBABfO+xaAHP4HPRF2cTC9vgvItTSm
'' SIG '' f83Qh8WIGjB/T8ObXAZz8OjuhUxjaaFdleMM0lBryPTQ
'' SIG '' M2qEJPe36zwbSI/mS83afsl3YTj+IQhQE7jU/kXjjytJ
'' SIG '' gnn0hvrV6hqWGd3rLAUt6vJy9lMDPjTLxLgXf9r5nWMQ
'' SIG '' wr8Myb9rEVKChHyfpzee5kH0F8HABBgr0UdqirZ7bowe
'' SIG '' 9Vj2AIMD8liyrukZ2iA/wdG2th9y1IsA0QF8dTXqvcnT
'' SIG '' mpfeQh35k5zOCPmSNq1UH410ANVko43+Cdmu4y81hjaj
'' SIG '' V/gxdEkMx1NKU4uHQcKfZxAvBAKqMVuqte69M9J6A47O
'' SIG '' vgRaPs+2ykgcGV00TYr2Lr3ty9qIijanrUR3anzEwlvz
'' SIG '' ZiiyfTPjLbnFRsjsYg39OlV8cipDoq7+qNNjqFzeGxcy
'' SIG '' tL5TTLL4ZaoBdqbhOhZ3ZRDUphPvSRmMThi0vw9vODRz
'' SIG '' W6AxnJll38F0cuJG7uEBYTptMSbhdhGQDpOXgpIUsWTj
'' SIG '' d6xpR6oaQf/DJbg3s6KCLPAlZ66RzIg9sC+NJpud/v4+
'' SIG '' 7RWsWCiKi9EOLLHfMR2ZyJ/+xhCx9yHbxtl5TPau1j/1
'' SIG '' MIDpMPx0LckTetiSuEtQvLsNz3Qbp7wGWqbIiOWCnb5W
'' SIG '' qxL3/BAPvIXKUjPSxyZsq8WhbaM2tszWkPZPubdcMIIG
'' SIG '' 7TCCBNWgAwIBAgIQCoDvGEuN8QWC0cR2p5V0aDANBgkq
'' SIG '' hkiG9w0BAQsFADBpMQswCQYDVQQGEwJVUzEXMBUGA1UE
'' SIG '' ChMORGlnaUNlcnQsIEluYy4xQTA/BgNVBAMTOERpZ2lD
'' SIG '' ZXJ0IFRydXN0ZWQgRzQgVGltZVN0YW1waW5nIFJTQTQw
'' SIG '' OTYgU0hBMjU2IDIwMjUgQ0ExMB4XDTI1MDYwNDAwMDAw
'' SIG '' MFoXDTM2MDkwMzIzNTk1OVowYzELMAkGA1UEBhMCVVMx
'' SIG '' FzAVBgNVBAoTDkRpZ2lDZXJ0LCBJbmMuMTswOQYDVQQD
'' SIG '' EzJEaWdpQ2VydCBTSEEyNTYgUlNBNDA5NiBUaW1lc3Rh
'' SIG '' bXAgUmVzcG9uZGVyIDIwMjUgMTCCAiIwDQYJKoZIhvcN
'' SIG '' AQEBBQADggIPADCCAgoCggIBANBGrC0Sxp7Q6q5gVrMr
'' SIG '' V7pvUf+GcAoB38o3zBlCMGMyqJnfFNZx+wvA69HFTBdw
'' SIG '' bHwBSOeLpvPnZ8ZN+vo8dE2/pPvOx/Vj8TchTySA2R4Q
'' SIG '' KpVD7dvNZh6wW2R6kSu9RJt/4QhguSssp3qome7MrxVy
'' SIG '' fQO9sMx6ZAWjFDYOzDi8SOhPUWlLnh00Cll8pjrUcCV3
'' SIG '' K3E0zz09ldQ//nBZZREr4h/GI6Dxb2UoyrN0ijtUDVHR
'' SIG '' XdmncOOMA3CoB/iUSROUINDT98oksouTMYFOnHoRh6+8
'' SIG '' 6Ltc5zjPKHW5KqCvpSduSwhwUmotuQhcg9tw2YD3w6yS
'' SIG '' SSu+3qU8DD+nigNJFmt6LAHvH3KSuNLoZLc1Hf2JNMVL
'' SIG '' 4Q1OpbybpMe46YceNA0LfNsnqcnpJeItK/DhKbPxTTuG
'' SIG '' oX7wJNdoRORVbPR1VVnDuSeHVZlc4seAO+6d2sC26/PQ
'' SIG '' PdP51ho1zBp+xUIZkpSFA8vWdoUoHLWnqWU3dCCyFG1r
'' SIG '' oSrgHjSHlq8xymLnjCbSLZ49kPmk8iyyizNDIXj//cOg
'' SIG '' rY7rlRyTlaCCfw7aSUROwnu7zER6EaJ+AliL7ojTdS5P
'' SIG '' WPsWeupWs7NpChUk555K096V1hE0yZIXe+giAwW00aHz
'' SIG '' rDchIc2bQhpp0IoKRR7YufAkprxMiXAJQ1XCmnCfgPf8
'' SIG '' +3mnAgMBAAGjggGVMIIBkTAMBgNVHRMBAf8EAjAAMB0G
'' SIG '' A1UdDgQWBBTkO/zyMe39/dfzkXFjGVBDz2GM6DAfBgNV
'' SIG '' HSMEGDAWgBTvb1NK6eQGfHrK4pBW9i/USezLTjAOBgNV
'' SIG '' HQ8BAf8EBAMCB4AwFgYDVR0lAQH/BAwwCgYIKwYBBQUH
'' SIG '' AwgwgZUGCCsGAQUFBwEBBIGIMIGFMCQGCCsGAQUFBzAB
'' SIG '' hhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wXQYIKwYB
'' SIG '' BQUHMAKGUWh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNv
'' SIG '' bS9EaWdpQ2VydFRydXN0ZWRHNFRpbWVTdGFtcGluZ1JT
'' SIG '' QTQwOTZTSEEyNTYyMDI1Q0ExLmNydDBfBgNVHR8EWDBW
'' SIG '' MFSgUqBQhk5odHRwOi8vY3JsMy5kaWdpY2VydC5jb20v
'' SIG '' RGlnaUNlcnRUcnVzdGVkRzRUaW1lU3RhbXBpbmdSU0E0
'' SIG '' MDk2U0hBMjU2MjAyNUNBMS5jcmwwIAYDVR0gBBkwFzAI
'' SIG '' BgZngQwBBAIwCwYJYIZIAYb9bAcBMA0GCSqGSIb3DQEB
'' SIG '' CwUAA4ICAQBlKq3xHCcEua5gQezRCESeY0ByIfjk9iJP
'' SIG '' 2zWLpQq1b4URGnwWBdEZD9gBq9fNaNmFj6Eh8/YmRDfx
'' SIG '' T7C0k8FUFqNh+tshgb4O6Lgjg8K8elC4+oWCqnU/ML9l
'' SIG '' Ffim8/9yJmZSe2F8AQ/UdKFOtj7YMTmqPO9mzskgiC3Q
'' SIG '' YIUP2S3HQvHG1FDu+WUqW4daIqToXFE/JQ/EABgfZXLW
'' SIG '' U0ziTN6R3ygQBHMUBaB5bdrPbF6MRYs03h4obEMnxYOX
'' SIG '' 8VBRKe1uNnzQVTeLni2nHkX/QqvXnNb+YkDFkxUGtMTa
'' SIG '' iLR9wjxUxu2hECZpqyU1d0IbX6Wq8/gVutDojBIFeRlq
'' SIG '' AcuEVT0cKsb+zJNEsuEB7O7/cuvTQasnM9AWcIQfVjnz
'' SIG '' rvwiCZ85EE8LUkqRhoS3Y50OHgaY7T/lwd6UArb+BOVA
'' SIG '' kg2oOvol/DJgddJ35XTxfUlQ+8Hggt8l2Yv7roancJIF
'' SIG '' cbojBcxlRcGG0LIhp6GvReQGgMgYxQbV1S3CrWqZzBt1
'' SIG '' R9xJgKf47CdxVRd/ndUlQ05oxYy2zRWVFjF7mcr4C34M
'' SIG '' j3ocCVccAvlKV9jEnstrniLvUxxVZE/rptb7IRE2lskK
'' SIG '' PIJgbaP5t2nGj/ULLi49xTcBZU8atufk+EMF/cWuiC7P
'' SIG '' OGT75qaL6vdCvHlshtjdNXOCIUjsarfNZzGCBUUwggVB
'' SIG '' AgEBMHowZjEbMBkGA1UECgwSVHJhbnNjcmliZSBQcm9q
'' SIG '' ZWN0MSIwIAYJKoZIhvcNAQkBFhNwaGFybWFrb3pAZ21h
'' SIG '' aWwuY29tMSMwIQYDVQQDDBpXYWx0ZXIgUGFibG8gVMOp
'' SIG '' bGxleiBBeWFsYQIQG1oaRsBcSrdP5jDUcb+hCzAJBgUr
'' SIG '' DgMCGgUAoHgwGAYKKwYBBAGCNwIBDDEKMAigAoAAoQKA
'' SIG '' ADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgor
'' SIG '' BgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkqhkiG
'' SIG '' 9w0BCQQxFgQU0i7xxK5tREcWSEc0usOENMGPNKgwDQYJ
'' SIG '' KoZIhvcNAQEBBQAEggEAhV48d3S7pp72owCiFkHCja0l
'' SIG '' oUq7sspiXMhdrchWAtbj9/f6KfK8nrqPzqIZX4CtdTRu
'' SIG '' ddS1UXDhm781UO5LLdPT2yS0rfR+PukcMI0Ha50X7Lwk
'' SIG '' HGLfMlFrFHMwAXnlLCQi6SxH36P9Hi5ew8EWVa8C3soO
'' SIG '' 6lc3+DssDe4nN7s6MHV4bjIvxZF8XnhPrbaZsK6k6vTQ
'' SIG '' irJHn4DTynJaM1P+p9vvH7NFOz45ZWTNIWwfvisjz4Fb
'' SIG '' 5VcWSRSaJ57xMT6+Z4CBjvTeOX5e9wZRvirLmsUUy9O6
'' SIG '' asPKb+12yCjg5FifFcyzxDBLlEMToReV3822PmlF0XfA
'' SIG '' zRnPDe6epKGCAyYwggMiBgkqhkiG9w0BCQYxggMTMIID
'' SIG '' DwIBATB9MGkxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5E
'' SIG '' aWdpQ2VydCwgSW5jLjFBMD8GA1UEAxM4RGlnaUNlcnQg
'' SIG '' VHJ1c3RlZCBHNCBUaW1lU3RhbXBpbmcgUlNBNDA5NiBT
'' SIG '' SEEyNTYgMjAyNSBDQTECEAqA7xhLjfEFgtHEdqeVdGgw
'' SIG '' DQYJYIZIAWUDBAIBBQCgaTAYBgkqhkiG9w0BCQMxCwYJ
'' SIG '' KoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0yNjAyMDMw
'' SIG '' MDUzMTdaMC8GCSqGSIb3DQEJBDEiBCAakM6V7tR0ilI6
'' SIG '' MB8gSEj/VNbrMR+e1UXyFlBSdhJ8sTANBgkqhkiG9w0B
'' SIG '' AQEFAASCAgBUKg0zQrDjgmZ2XjL9gg1c4BNr/xBxZvJq
'' SIG '' eGoqc4A+0tVBeCyk3N7jWpxYJy7BAcc+NPRIgKzPwSdo
'' SIG '' zZeethI0pBnhZp81GpAHtlQRNlRspoo8VFVdnrvCvuAO
'' SIG '' 7THk1xEIfnTJzhlqw4kZqfFtH+Rf9a0zYB6Z5xZ3YQe7
'' SIG '' dtWtrbcBZz1H36AWVE9amrOBoSlvghle7XX/lyUbGUAA
'' SIG '' EoWIXVwgEENlGRa2JKthd6eAlBy1UjxdtJEPUTvhqrf4
'' SIG '' RM+U9YRGnbUWtagpJP1zTAfXWbQW0IJaqXAyAhXsWDSl
'' SIG '' lG+TFQSItbJ2tGpz+z3yeudxFTbrMLrJltDOr48v6loV
'' SIG '' rWSk/x0PHsw+JwdfydtfsRS0HC0ZyRx/miGmn0KnVBXL
'' SIG '' xHPTt2NNQ/Pe3SGFPp9JdS167PPkZRhmhU7wqXZj4Lhq
'' SIG '' /NpxJoSVtbsIXj1Cg5Sa4OP8FWBnhnXhMqNEVaUdrHzt
'' SIG '' arNbeGDqbmcKUaUhF0rdod4sDXfI1inO77Uu50OrWuy6
'' SIG '' ZPHGCVm06P0+Vc9goqIyWP03boG1DKLvjOAJGA69/4tN
'' SIG '' IfmmRafaNlG012Dv77h3sD763LxAVA8YxACzfZjzKI8B
'' SIG '' AfxnIxwCpBb3SYKTuNzYuQYoMSN+uSJ1V1TUyjWrb2fZ
'' SIG '' /LRYvARtpmJACGzbEyv0ZX+zykGo7DR3DA==
'' SIG '' End signature block
